stages:
  - check
  - build
  - test

flake8:
  image: rustdocker/rust:stable
  stage: check
  script:
    - apt-get update
    - apt-get install -y flake8
    - flake8 python
  allow_failure: true

cargo:build:
  image: rustdocker/rust:stable
  stage: build
  script:
    - apt-get update
    - apt-get install -y capnproto
    - cargo install capnpc
    - ./build_capnp.sh
    - cargo build --all-features --release --verbose --jobs 1
  artifacts:
    paths:
      - target
    expire_in: 6h

pytest:
  image: rustdocker/rust:stable
  stage: test
  script:
    - apt-get update
    - apt-get install -y capnproto python3-dev python3-pip
    - pip3 install --upgrade pip
    - pip3 install pycapnp cloudpickle pytest pytest-timeout
    - RAIN_TEST_BIN=${PWD}/target/release/rain pytest -x -v --timeout=20
  artifacts:
    when: on_failure
    paths:
      - tests/pytests/work
    expire_in: 1d
    
cargo:test:
  image: rustdocker/rust:stable
  stage: test
  script:
    - apt-get update
    - apt-get install -y capnproto
    - cargo install capnpc
    - ./build_capnp.sh
    - cargo test --all-features