[package]
name = "rain"
version = "0.1.0"
authors = [
    "Stanislav Bohm <spirali@kreatrix.org>",
    "Tomas Gavenciak <gavento@ucw.cz>",
    "Vojtech Cima <cima.vojtech@gmail.com>",
    ]
build = "build.rs"

[lib]
name = "librain"
path = "src/lib.rs"

[[bin]]
name = "rain"
path = "src/bin.rs"

[dependencies]
error-chain="*"
bitflags = "1.0.0"
capnp = "*"
capnp-rpc = "*"
clap = "*"
log = "*"
futures="*"
tokio-core="*"
tokio-io="*"
tokio-timer = "*"
tokio-uds="*"
tokio-process="*"
env_logger = "*"
arrayref = "*"
num_cpus = "*"
nix = "*"
lazy_static = "*"
bytes = "*"
sysconf = "*"
sys-info = "*"

[build-dependencies]
capnpc = "0.8"

