[package]
name = "rain"
version = "0.1.0"
authors = [
    "Stanislav Bohm <spirali@kreatrix.org>",
    "Tomas Gavenciak <gavento@ucw.cz>"
    ]
build = "build.rs"

[lib]
name = "librain"
path = "src/lib.rs"

[[bin]]
name = "rain"
path = "src/bin.rs"

[dependencies]
bitflags = "*"
capnp = "*"
capnp-rpc = "*"
clap = "*"
log = "*"
futures="*"
tokio-core="*"
tokio-io="*"
env_logger = "*"
arrayref = "*"
num_cpus = "*"

[build-dependencies]
capnpc = "0.8"

