[package]
name = "rain"
version = "0.1.0"
authors = [
    "Stanislav Bohm <spirali@kreatrix.org>",
    "Tomas Gavenciak <gavento@ucw.cz>"
    ]
build = "build.rs"

[dependencies]
bitflags = "*"
capnp = "*"

[build-dependencies]
capnpc = "0.8"
