[package]
name = "rain_task_test"
version = "0.1.0"
authors = ["Tomas Gavenciak <gavento@ucw.cz>"]

[dependencies]
rain-task = { path = "../rain-task" }
serde_derive = "*"
serde = "*"
serde_json = "*"
rmp-serde = "*"
rmp = "*"
