[package]
name = "rain-task"
version = "0.1.0"
authors = ["Tomas Gavenciak <gavento@ucw.cz>"]

[dependencies]
rain = { path = ".." }
atty="*"
error-chain="*"
clap = "*"
log = ">=0.4"
futures="0.1"
tokio-core="*"
tokio-io="*"
tokio-timer = "*"
tokio-uds="*"
tokio-process="*"
env_logger = "*"
arrayref = "*"
num_cpus = "*"
nix = "*"
lazy_static = "*"
bytes = "*"
tempdir = "*"
memmap = "*"
sysconf = "*"
sys-info = "*"
chrono = { version = "*", features = ["serde"] }
serde_derive = "*"
serde = "*"
serde_json = "*"
tar = "*"
toml = "*"
walkdir = "*"
rmp-serde = "*"
rmp = "*"